//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class analogs
    {
        public int Id { get; set; }
        public Nullable<int> ComponentId { get; set; }
        public string AnalogId { get; set; }
    
        public virtual component component { get; set; }
        public virtual component component1 { get; set; }
    }
}
