//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class component
    {
        public component()
        {
            this.project = new HashSet<project>();
        }
    
        public int ComponentId { get; set; }
        public string NameAndVersion { get; set; }
        public string VendorLink { get; set; }
        public Nullable<int> CtiticalityLevel { get; set; }
    
        public virtual analogs analogs { get; set; }
        public virtual analogs analogs1 { get; set; }
        public virtual criticality_level criticality_level { get; set; }
        public virtual ICollection<project> project { get; set; }
    }
}
