//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class criticality_level
    {
        public criticality_level()
        {
            this.component = new HashSet<component>();
        }
    
        public int Id { get; set; }
        public string CriticalityLevel { get; set; }
    
        public virtual ICollection<component> component { get; set; }
    }
}
