//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;

namespace DAL
{
   
    public class DiplomaContext : DbContext
    {
        public DiplomaContext() : base("conn")
        { }

        public DbSet<project> Projects { get; set; }
        public DbSet<component> Components { get; set; }
        public DbSet<analogs> Analogs { get; set; }
        public DbSet<criticality_level> CriticalityLevels { get; set; }
    }

}
